### ISSUE TITLE
invalid unit price

### ISSUE THREAD

**Issue by machine-creek** [klaytn/caver-java#318]
This is the parameter
gas price 25000000000
limit 21000
chainId 8217
request

{
"id": "1",
"jsonrpc": "2.0",
"method": "klay_sendRawTransaction",
"params": [
"0x08f885238505d21dba00825208940282c0f32b1816dfdb0ba60059a4f25109a73fc1872386f26fc1000094d73d9aa55abbd6cfbed3e9ad7f8be2f6d83c70dcf847f845824056a087fc7935f42ff1ea908960cb7175a768ccb3f77b219cd913ca8038a9f4deabc2a023d1183bca467003397c7c71f4336de09397c444684d39afe78a01753d3fae5a"
]
}

response:
{
"jsonrpc": "2.0",
"id": "1",
"error": {
"code": -32000,
"message": "invalid unit price"
}
}

RPC:https://api.baobab.klaytn.net:8651/

[https://github.com/klaytn/caver-java/issues/142#issuecomment-657300291](url)

https://docs.klaytn.com/bapp/sdk/caver-js/v1.4.1#caution-when-sending-a-transaction-to-klaytn
The document link is invalid

**Comment by aeharvlee** [comment]
@machine-creek 

The gas price of Cypress mainnet was adjusted to 750 ston(= 30 * 25000000000).
Reference: https://medium.com/klaytn/cypress-hard-fork-starts-today-663abd517e6d

You must give gasPrice value as `750000000000(=30 * 25000000000)`.

My recommendation:
Before sending trasnsaction, fetch gasPrice from network using `caver.rpc.klay.getGasPrice()` and use that returned value to gasPrice field instead of using Hard Coded value.

cc. @sirano11

**Comment by machine-creek** [comment]
Ok, thank you. Let me try

**Comment by machine-creek** [comment]
Thank you. The test was successful.

[0xca1a12c892c9db640d0033a928c99c6177652b17247ab59ec00aa584f3d8eeab](https://scope.klaytn.com/tx/0xca1a12c892c9db640d0033a928c99c6177652b17247ab59ec00aa584f3d8eeab)
